version: 0.0
os: linux

files:
  - source: /home/ec2-user/springapp-repo
    destination: /home/ec2-user/spring-app-target

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 60
      runas: ec2-user